In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv('/content/adult.csv')

read the data

In [ ]:
data

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38459,42,Private,341757,Some-college,10,Never-married,Machine-op-inspct,Not-in-family,White,Female,0.0,0.0,40.0,United-States,<=50K
38460,36,Private,218542,HS-grad,9,Separated,Adm-clerical,Unmarried,Black,Female,0.0,0.0,40.0,United-States,<=50K
38461,44,Local-gov,190020,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
38462,27,Private,221436,Bachelors,13,Married-civ-spouse,Adm-clerical,Wife,White,Female,0.0,0.0,40.0,Cuba,>50K
38463,39,Self-emp-not-inc,52187,HS-grad,9,Married-civ-spouse,Exec-ma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Display the first 5 rows of the dataset.

In [ ]:
data.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K

In [ ]:
data.shape

(38464, 15)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38464 entries, 0 to 38463
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              38464 non-null  int64
 1   workclass        38464 non-null  object
 2   fnlwgt           38464 non-null  int64
 3   education        38464 non-null  object
 4   educational-num  38464 non-null  int64
 5   marital-status   38464 non-null  object
 6   occupation       38464 non-null  object
 7   relationship     38463 non-null  object
 8   race             38463 non-null  object
 9   gender           38463 non-null  object
 10  capital-gain     38463 non-null  float64
 11  capital-loss     38463 non-null  float64
 12  hours-per-week   38463 non-null  float64
 13  native-country   38463 non-null  object
 14  income           38463 non-null  object
dtypes: float64(3), int64(3), object(9)
memory usage: 4.4+ MB

In [ ]:
data.dtypes

age                  int64
workclass           object
fnlwgt               int64
education           object
educational-num      int64
marital-status      object
occupation          object
relationship        object
race                object
gender              object
capital-gain       float64
capital-loss       float64
hours-per-week     float64
native-country      object
income              object
dtype: object

In [ ]:
data.describe()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,38464.000000,3.846400e+04,38464.000000,38463.000000,38463.000000,38463.000000
mean,38.667169,1.896262e+05,10.078177,1065.475496,87.533760,40.400567
std,13.751014,1.054150e+05,2.560065,7411.847122,402.473518,12.363217
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.176825e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.377350e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

summary of the DataFrame

In [ ]:
summary=data.describe()

In [ ]:
summary

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,38464.000000,3.846400e+04,38464.000000,38463.000000,38463.000000,38463.000000
mean,38.667169,1.896262e+05,10.078177,1065.475496,87.533760,40.400567
std,13.751014,1.054150e+05,2.560065,7411.847122,402.473518,12.363217
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.176825e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.377350e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

descriptive statistics for numeric columns

In [ ]:
data1=data.select_dtypes(include="number")
data1.describe()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,38464.000000,3.846400e+04,38464.000000,38463.000000,38463.000000,38463.000000
mean,38.667169,1.896262e+05,10.078177,1065.475496,87.533760,40.400567
std,13.751014,1.054150e+05,2.560065,7411.847122,402.473518,12.363217
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.176825e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.377350e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

Display the column names of the DataFrame.

In [ ]:
data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

unique values in the 'workclass' column.

In [ ]:
data.nunique()

age                   73
workclass              9
fnlwgt             24332
education             16
educational-num       16
marital-status         7
occupation            16
relationship           6
race                   5
gender                 2
capital-gain         122
capital-loss          98
hours-per-week        95
native-country        42
income                 2
dtype: int64

In [ ]:
data['workclass'].unique()

array(['Private', 'Local-gov', '?', 'Self-emp-not-inc', 'Federal-gov',
       'State-gov', 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

Create a new column 'income_binary' where <=50K is 0 and >50K is 1.

In [ ]:
data2 = pd.DataFrame(data,columns=["age","workclass","fnlwgt","education","educational-num","marital-status","occupation","relationship","race","gender","capital-gain","capital-loss","hours-per-week","native-country","income"])
data2
data2['income_binary']=data2['income'].apply(lambda x: 0 if x=='<=50k'else 1)
data2

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,income_binary
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K,1
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K,1
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K,1
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K,1
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38459,42,Private,341757,Some-college,10,Never-married,Machine-op-inspct,Not-in-family,White,Female,0.0,0.0,40.0,United-States,<=50K,1
38460,36,Private,218542,HS-grad,9,Separated,Adm-clerical,Unmarried,Black,Female,0.0,0.0,40.0,United-States,<=50K,1
38461,44,Local-gov,190020,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K,1
38462,27,Private,221436,Bachelors,13,Married-civ-spouse,Adm-clerical,Wife,White,Female,0.0,0.0,40.0,Cuba,>50K,1
38463,39,Self-emp-not-inc,52187,HS-grad,9,Married-civ-spouse,Exec-ma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

Create a new column 'age_group' categorizing ages into 'Youth' (< 30), 'Adult' (30-60), and 'Senior' (60+).

In [ ]:
data2=pd.DataFrame(data)

In [ ]:
def categorize_age(age):
    if age < 30:
        return 'Youth'
    elif age >= 30 and age < 60:
        return 'Adult'
    else:
        return 'Senior'

In [ ]:
data2['age_group']=data2['age'].apply(categorize_age)

In [ ]:
data2

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,age_group
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K,Youth
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K,Adult
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K,Youth
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K,Adult
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K,Youth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38459,42,Private,341757,Some-college,10,Never-married,Machine-op-inspct,Not-in-family,White,Female,0.0,0.0,40.0,United-States,<=50K,Adult
38460,36,Private,218542,HS-grad,9,Separated,Adm-clerical,Unmarried,Black,Female,0.0,0.0,40.0,United-States,<=50K,Adult
38461,44,Local-gov,190020,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K,Adult
38462,27,Private,221436,Bachelors,13,Married-civ-spouse,Adm-clerical,Wife,White,Female,0.0,0.0,40.0,Cuba,>50K,Youth
38463,39,Self-emp-not-inc,52187,HS-grad,9,Married-civ-spouse,Exec-ma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adult

In [ ]:
data2

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,income_binary
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K,1
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K,1
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K,1
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K,1
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38459,42,Private,341757,Some-college,10,Never-married,Machine-op-inspct,Not-in-family,White,Female,0.0,0.0,40.0,United-States,<=50K,1
38460,36,Private,218542,HS-grad,9,Separated,Adm-clerical,Unmarried,Black,Female,0.0,0.0,40.0,United-States,<=50K,1
38461,44,Local-gov,190020,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K,1
38462,27,Private,221436,Bachelors,13,Married-civ-spouse,Adm-clerical,Wife,White,Female,0.0,0.0,40.0,Cuba,>50K,1
38463,39,Self-emp-not-inc,52187,HS-grad,9,Married-civ-spouse,Exec-ma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

Rename the 'educational-num' column to 'education_num'.

In [ ]:
data.rename(columns={'educational-num':'education_num'})

,age,workclass,fnlwgt,education,education_num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38459,42,Private,341757,Some-college,10,Never-married,Machine-op-inspct,Not-in-family,White,Female,0.0,0.0,40.0,United-States,<=50K
38460,36,Private,218542,HS-grad,9,Separated,Adm-clerical,Unmarried,Black,Female,0.0,0.0,40.0,United-States,<=50K
38461,44,Local-gov,190020,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
38462,27,Private,221436,Bachelors,13,Married-civ-spouse,Adm-clerical,Wife,White,Female,0.0,0.0,40.0,Cuba,>50K
38463,39,Self-emp-not-inc,52187,HS-grad,9,Married-civ-spouse,Exec-ma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Replace the missing values represented by '?' in 'workclass' and 'occupation' columns with 'Unknown'.

In [ ]:
data2=pd.DataFrame(data)

In [ ]:
data2['workclass']=data2['workclass'].replace('?','unknown')
data2['occupation']=data2['occupation'].replace('?','unknown')

In [ ]:
data2

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K
4,18,unknown,103497,Some-college,10,Never-married,unknown,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38459,42,Private,341757,Some-college,10,Never-married,Machine-op-inspct,Not-in-family,White,Female,0.0,0.0,40.0,United-States,<=50K
38460,36,Private,218542,HS-grad,9,Separated,Adm-clerical,Unmarried,Black,Female,0.0,0.0,40.0,United-States,<=50K
38461,44,Local-gov,190020,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
38462,27,Private,221436,Bachelors,13,Married-civ-spouse,Adm-clerical,Wife,White,Female,0.0,0.0,40.0,Cuba,>50K
38463,39,Self-emp-not-inc,52187,HS-grad,9,Married-civ-spouse,Exec-ma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
Calculate the average age for each workclass.

SyntaxError: invalid syntax (<ipython-input-39-e23fa7f33456>, line 1)

In [ ]:
average_age_by_workclass=data.groupby('workclass')['age'].mean()
average_age_by_workclass

workclass
?                   39.759819
Federal-gov         42.181185
Local-gov           41.803787
Never-worked        18.714286
Private             36.960111
Self-emp-inc        45.823838
Self-emp-not-inc    45.329229
State-gov           39.420206
Without-pay         43.857143
Name: age, dtype: float64

Find the total capital-gain for each gender.

In [ ]:
total_capital_gain_by_gender = data.groupby('gender')['capital-gain'].sum()
total_capital_gain_by_gender

gender
Female     7628551.0
Male      33352833.0
Name: capital-gain, dtype: float64

Get the count of each marital-status category.

In [ ]:
marital_status_counts=data2['marital-status'].value_counts()

In [ ]:
marital_status_counts

marital-status
Married-civ-spouse       17550
Never-married            12734
Divorced                  5250
Widowed                   1204
Separated                 1195
Married-spouse-absent      502
Married-AF-spouse           29
Name: count, dtype: int64

Find the mean hours-per-week worked by individuals in different education levels.

In [ ]:
mean_hours_per_education_level = data2.groupby('education')['hours-per-week'].mean()

In [ ]:
mean_hours_per_education_level

education
10th            37.460274
11th            34.438108
12th            35.177419
1st-4th         38.401070
5th-6th         38.911616
7th-8th         39.222819
9th             38.326496
Assoc-acdm      41.040453
Assoc-voc       41.586313
Bachelors       42.299717
Doctorate       46.678337
HS-grad         40.585619
Masters         43.667144
Preschool       36.000000
Prof-school     47.695375
Some-college    38.802921
Name: hours-per-week, dtype: float64

Calculate the mean, median, and standard deviation of 'fnlwgt' for each race.

In [ ]:
fnlwgt_stats_by_race = data2.groupby('race')['fnlwgt'].agg(['mean', 'median', 'std'])

In [ ]:
fnlwgt_stats_by_race

                             mean    median            std
race
Amer-Indian-Eskimo  115886.323529  100584.0   94451.192057
Asian-Pac-Islander  159982.348420  141297.0   88174.631727
Black               232027.728412  210259.0  127761.100067
Other               196616.000000  186990.0   94766.081588
White               186726.022020  177275.0  101953.419223

Get the unique values and their counts for the 'native-country' column

In [ ]:
native_country_counts = data2['native-country'].value_counts()

In [ ]:
native_country_counts

native-country
United-States                 34548
Mexico                          735
?                               667
Philippines                     232
Germany                         162
Puerto-Rico                     155
Canada                          150
El-Salvador                     112
Cuba                            111
India                           109
England                         106
China                            99
South                            91
Dominican-Republic               80
Jamaica                          79
Italy                            78
Japan                            74
Poland                           73
Guatemala                        69
Haiti                            66
Vietnam                          66
Columbia                         64
Portugal                         55
Taiwan                           51
Iran                             50
Greece                           41
Nicaragua                        37
Ecuador                          36
Peru                             33
Ireland                          32
France                           26
Cambodia                         24
Thailand                         24
Hong                             20
Scotland                         17
Outlying-US(Guam-USVI-etc)       17
Yugoslavia                       16
Trinadad&Tobago                  16
Honduras                         15
Hungary                          14
Laos                             12
Holand-Netherlands                1
Name: count, dtype: int64

Filter the dataset to include only individuals with income >50K.

In [ ]:
filtered_data = data2[data['income'] == '>50K']

In [ ]:
filtered_data.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K
7,63,Self-emp-not-inc,104626,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103.0,0.0,32.0,United-States,>50K
10,65,Private,184454,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,6418.0,0.0,40.0,United-States,>50K
14,48,Private,279724,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3103.0,0.0,48.0,United-States,>50K

Sort the dataset by age in descending order.

In [ ]:
sorted_data = data.sort_values(by='age', ascending=False)
sorted_data

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
34558,90,Private,311184,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0.0,0.0,20.0,?,<=50K
20351,90,Private,313986,11th,7,Never-married,Handlers-cleaners,Own-child,White,Male,0.0,0.0,40.0,United-States,<=50K
15088,90,Private,197613,HS-grad,9,Never-married,Adm-clerical,Not-in-family,White,Female,0.0,0.0,40.0,United-States,>50K
7419,90,Self-emp-not-inc,122348,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,20051.0,0.0,45.0,United-States,>50K
8427,90,Federal-gov,311184,Masters,14,Divorced,Prof-specialty,Not-in-family,White,Male,0.0,0.0,99.0,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35471,17,Private,29571,12th,8,Never-married,Handlers-cleaners,Own-child,White,Male,0.0,0.0,15.0,United-States,<=50K
2646,17,Private,91141,10th,6,Never-married,Sales,Own-child,White,Male,0.0,0.0,8.0,United-States,<=50K
26952,17,Private,33138,12th,8,Never-married,Sales,Own-child,White,Male,0.0,0.0,40.0,United-States,<=50K
13295,17,Private,233781,11th,7,Never-married,Other-service,Own-child,Black,Male,0.0,0.0,18.0,United-States,<=50K
7012,17,Self-emp-not-inc,33230,11th,7,Never-married,Farming-fishing,Own-child,White,Male,0.0,0.0,15.0,United-States,<=50K

Filter the dataset to include only individuals who work more than 40 hours per week.

In [ ]:
filtered_data = data[data['hours-per-week'] > 40]

In [ ]:
filtered_data

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
14,48,Private,279724,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3103.0,0.0,48.0,United-States,>50K
15,43,Private,346189,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,50.0,United-States,>50K
19,40,Private,85019,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,45.0,?,>50K
20,34,Private,107914,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0.0,0.0,47.0,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38443,30,Private,167476,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
38449,21,Private,206008,Some-college,10,Never-married,Adm-clerical,Own-child,Black,Male,0.0,0.0,50.0,United-States,<=50K
38452,43,Private,27766,Bachelors,13,Separated,Exec-managerial,Unmarried,White,Male,0.0,0.0,60.0,United-States,>50K
38456,35,Self-emp-inc,187046,Masters,14,Married-civ-spouse,Adm-clerical,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
38461,44,Local-gov,190020,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K

In [ ]:
Calculate the percentage of missing values in each column.

In [ ]:
missing_values_percentage = data.isnull().mean() * 100
missing_values_percentage

age                0.0000
workclass          0.0000
fnlwgt             0.0000
education          0.0000
educational-num    0.0000
marital-status     0.0000
occupation         0.0000
relationship       0.0026
race               0.0026
gender             0.0026
capital-gain       0.0026
capital-loss       0.0026
hours-per-week     0.0026
native-country     0.0026
income             0.0026
dtype: float64

Calculate the median income by education level and gender.

Find the top 3 occupations with the highest average capital-gain.

In [ ]:
avg_capital_gain_by_occupation = data.groupby('occupation')['capital-gain'].mean()

In [ ]:
top_3_occupations = avg_capital_gain_by_occupation.sort_values(ascending=False).head(3)

In [ ]:
top_3_occupations.head()

occupation
Prof-specialty     2746.224372
Exec-managerial    2158.955970
Sales              1255.387037
Name: capital-gain, dtype: float64

Filter the dataset to include individuals who are 'Married-civ-spouse' and have an income >50K.

In [ ]:
filtered_data = data[(data['marital-status'] == 'Married-civ-spouse') & (data['income'] == '>50K')]

filtered_data.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K
7,63,Self-emp-not-inc,104626,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103.0,0.0,32.0,United-States,>50K
10,65,Private,184454,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,6418.0,0.0,40.0,United-States,>50K
14,48,Private,279724,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3103.0,0.0,48.0,United-States,>50K